#!/usr/bin/env bash

dir=`dirname "$0"`
pushd "$dir"

gunicorn --bind=127.0.0.1:5000 \
         --workers=5 \
         src.webstruct-demo.__init__:webstruct_demo \
         --log-file=- \
         --error-logfile=- \
         --access-logfile=-

popd
