#!env sh

dir=`dirname "$0"`
pushd "$dir"

gunicorn --bind=0.0.0.0:5001 \
         --workers=5 \
         src.webstruct-demo.__init__:webstruct_demo \
         --log-file=- \
         --error-logfile=- \
         --access-logfile=-

popd
